my_app/features/models.py
from my_app import db

# https://media.readthedocs.org/pdf/flask-restless/latest/flask-restless.pdf
# Create your Flask-SQLALchemy models as usual but with the following
# restriction: they must have an __init__ method that accepts keyword
# arguments for all columns (the constructor in
# flask_sqlalchemy.SQLAlchemy.Model supplies such a method, so you
# don't need to declare a new one).
class Feature(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    description = db.Column(db.Text(2048))
    priority = db.Column(db.Integer)
    target_date = db.Column(db.Date)

    area_id = db.Column(db.Integer, db.ForeignKey('area.id'))
    area = db.relationship(
        'Area', backref=db.backref('features', lazy='dynamic')
    )

    client_id = db.Column(db.Integer, db.ForeignKey('client.id'))
    client = db.relationship(
        'Client', backref=db.backref('features', lazy='dynamic')
    )

    def __repr__(self):
        return '<Feature %d>' % self.id

class Area(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))

    def __repr__(self):
        return '<Area %d>' % self.id

class Client(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))

    def __repr__(self):
        return '<Client %d>' % self.id

# populate 'static' tables
def populate():
    for client in ['Client A', 'Client B', 'Client C']:

        dup = False
        for c in Client.query.distinct(Client.name):
            if client == c.name:
                dup = True
                break
        if dup:
            continue

        c = Client(name=client)
        db.session.add(c)
        db.session.commit()

    for area in ['Policies', 'Billing', 'Claims', 'Reports']:

        dup = False
        for a in Area.query.distinct(Area.name):
            if area == a.name:
                dup = True
                break
        if dup:
            continue

        a = Area(name=area)
        db.session.add(a)
        db.session.commit()

    # TODO possibly make populate cooler with --- $ sqlite3 features.db < features.sql

my_app/features/forms.py
from flask_wtf import Form
from wtforms import TextField, TextAreaField, SelectField, DateField, IntegerField
from wtforms.validators import InputRequired, NumberRange, Optional, ValidationError
from wtforms.widgets import Select, html_params, HTMLString
from my_app.features.models import Client, Area
from decimal import Decimal

### Forms ###
# https://wtforms.readthedocs.io/en/latest/widgets.html
class CustomClientInput(Select): # custom radio button widget

    def __call__(self, field, **kwargs):
        kwargs.setdefault('id', field.id)
        html = []
        for val, label, selected in field.iter_choices():
            html.append(
                '<input type="radio" %s> %s' % (
                    html_params(
                        name=field.name, value=val, checked=selected, **kwargs
                    ), label
                )
            )
        return HTMLString(' '.join(html))

class ClientField(SelectField): # custom field
    widget = CustomClientInput()

    def iter_choices(self):
        clients = [(c.id, c.name) for c in Client.query.all()]
        for value, label in clients:
            yield (value, label, self.coerce(value) == self.data)

    def pre_validate(self, form):

        for v, _ in [(c.id, c.name) for c in Client.query.all()]:
            if self.data == v:
                break
            else:
                pass
                # raise ValueError(self.gettext('Not a valid choice')) # TODO this needs work

class AreaField(SelectField): # custom field
    widget = CustomClientInput()

    def iter_choices(self):
        areas = [(c.id, c.name) for c in Area.query.all()]
        for value, label in areas:
            yield (value, label, self.coerce(value) == self.data)

    def pre_validate(self, form):

        for v, _ in [(c.id, c.name) for c in Client.query.all()]:
            if self.data == v:
                break
            else:
                pass

class FeatureForm(Form):
    title = TextField('Title', validators=[InputRequired()])
    client = ClientField(
        'Client', validators=[InputRequired()], coerce=int
    )
    area = AreaField(
        "Product Area", validators=[InputRequired()], coerce=int
    )
    priority = IntegerField('Priority', validators=[
        InputRequired(), NumberRange(min=Decimal('0'))
    ])
    description = TextAreaField('Description', validators=[InputRequired()])
    target_date = DateField('Target Date (YYYY-mm-dd)', format='%Y-%m-%d', validators=[InputRequired()])

my_app/features/__init__.py
from my_app import db
from my_app.features.models import populate

db.create_all()
populate()

my_app/features/views.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
# from my_app import manager # TODO future feature for RESTfulness
from my_app import application, db
from my_app.features.models import Feature, Area, Client
from my_app.features.forms import FeatureForm
from my_app.decorators import template_or_json

# # Flask-Restless - db only - implicit routes ~/api/<db.model.classname>
# manager.create_api(Feature, methods=['GET', 'POST', 'DELETE']) # TODO future feature for RESTfulness
# manager.create_api(Client, methods=['GET', 'POST', 'DELETE']) # TODO future feature for RESTfulness
# manager.create_api(Area, methods=['GET', 'POST', 'DELETE']) # TODO future feature for RESTfulness
# # can use custom processors to customize handling of the requests
# # see  -  https://flask-restless.readthedocs.io/en/latest/processors.html

featreq = Blueprint('features', __name__)

@featreq.route('/')
@featreq.route('/home')
@template_or_json('home.html')
def home():
    # return render_template('home.html')
    fs = Feature.query.all()
    return {'count': len(fs)}

@featreq.route('/feature/<id>')
def feature(id):
    f = Feature.query.get_or_404(id)
    return render_template('feature.html', feature=f)


@featreq.route('/features/')
@featreq.route('/features/<int:page>')
def features(page=1):
    fs = Feature.query.paginate(page, 10)
    return render_template('features.html', features=fs)

@featreq.route('/feature-create', methods=['GET', 'POST'])
def create_feature():
    form = FeatureForm(request.form, csrf_enabled=False)

    # clients = [(c.id, c.name) for c in Client.query.all()]
    # form.clients.choices = clients

    if form.validate_on_submit(): # this is a POST

        title = form.title.data
        client = Client.query.get_or_404(form.client.data)
        priority = form.priority.data
        target_date = form.target_date.data
        area = Area.query.get_or_404(form.area.data)
        description = form.description.data

        f = Feature(
            title=title,
            client=client,
            priority=priority,
            target_date=target_date,
            area=area,
            description=description
        )
        maybe_adjust_priority(f)
        db.session.add(f)
        db.session.commit()
        flash('The feature %s has been created' % title, 'success')
        return redirect(url_for('features.feature', id=f.id))

    if form.errors:
        flash(form.errors, 'danger')

    return render_template('feature-create.html', form=form)

@application.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

def maybe_adjust_priority(new_feature):
    '''
    When adding a new feature, adjust the feature priorities if there is conflict
    with any of the existing features. Recursively check until all the lower
    priority features have been shifted to their next lower priority (higher number)
    :param: Feature object
    :return: None
    '''

    client_features = get_client_features(new_feature.client.name)

    for f in client_features:
        if f.priority == new_feature.priority and f is not new_feature:
            adjust_priorities(client_features, new_feature)

# there was a conflict, need to adjust priorities
def adjust_priorities(features, new_feature):
    new_priority = new_feature.priority
    for f in features:
        if f.priority == new_priority and f is not new_feature:
            f.priority += 1
            db.session.commit()
            maybe_adjust_priority(f)

# get the features for a client
def get_client_features(clientname):

    all_features = Feature.query.all()
    client_features = []
    for f in all_features:
        if f.client.name == clientname:
            client_features.append(f)

    return client_features

my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Feature Request</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('features.home') }}">Go to the home page</a>
        </div>
      </div>
    </div>
    <div class="container">
      <br/>
      <div>
        {% for client, message in get_flashed_messages(with_categories=true) %}
          <div class="alert alert-{{client}} alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      </div>
      {% block container %}{% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        {% block scripts %}

        {% endblock %}
  </body>
</html>

my_app/templates/feature-create.html
{% extends 'home.html' %}

{% block container %}
  <a href="{{ url_for('features.features') }}" id="features_link">
      See the features
  </a>
  <div class="top-pad">
    <form method="POST"
        action="{{ url_for('features.create_feature') }}" role="form"
        enctype="multipart/form-data">
      <div class="form-group">{{ form.title.label }}: {{ form.title() }}</div>
      <div class="form-group">{{ form.client.label }}: {{ form.client() }}</div>
      <div class="form-group">{{ form.area.label }}: {{ form.area() }}</div>
      <div class="form-group">{{ form.priority.label }}: {{ form.priority() }}</div>
      <div class="form-group">{{ form.target_date.label }}: {{ form.target_date() }}</div>
      <div class="form-group">{{ form.description.label }}: {{ form.description(cols='70', rows='15') }}</div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
{% endblock %}

{% block scripts %}
<script>
$(document).ready(function(){
  $.getJSON("/home", function(data) {
    $('#features_link').append('<span class="badge">' + data.count + '</span>');
  });
});
</script>
{% endblock %}

my_app/templates/feature.html
{% extends 'home.html' %}

{% block container %}
  <a href="{{ url_for('features.features') }}" id="features_link">
      See the features
  </a>
    <br><br>
  <a href="{{ url_for('features.create_feature') }}">
      Create a new feature request
  </a>
  <div class="top-pad">
    <h1><small></small>{{ feature.title }}</h1>
    <h4><small>Client </small>{{ feature.client.name }}</h4>
    <h4><small>Priority </small>{{ feature.priority }}</h4>
    <h4><small>Target Date </small>{{ feature.target_date }}</h4>
    <h4><small>Product Area </small>{{ feature.area.name }}</h4>
      <h4><small><u>Description </u><br>{{ feature.description }}</small></h4>
  </div>
{% endblock %}

{% block scripts %}
<script>
$(document).ready(function(){
  $.getJSON("/home", function(data) {
    $('#features_link').append('<span class="badge">' + data.count + '</span>');
  });
});
</script>
{% endblock %}

my_app/templates/features.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    {% for feature in features.items %}
      <div class="well">
        <h2>
          <a href="{{ url_for('features.feature', id=feature.id) }}">{{ feature.title }}</a>
          <small> for {{ feature.client.name }} priority {{ feature.priority }}</small>
        </h2>
      </div>
    {% endfor %}
    {% if features.has_prev %}
      <a href="{{ url_for('features.features', page=features.prev_num) }}">
        {{"<< Previous Page"}}
      </a>
    {% else %}
      {{"<< Previous Page"}}
    {% endif %} |
    {% if features.has_next %}
      <a href="{{ url_for('features.features', page=features.next_num) }}">
        {{"Next page >>"}}
      </a>
    {% else %}
      {{"Next page >>"}}
    {% endif %}
  </div>
{% endblock %}

my_app/templates/home.html
{% extends 'base.html' %}

{% block container %}
  <h4>Welcome to the feature request app</h4>
     <div class="navbar-header">
        <a class="navbar-brand" href="{{ url_for('features.create_feature') }}">
            Create a new feature request
        </a>
      </div>
    </br>
  <a href="{{ url_for('features.features') }}" id="features_link">
      See the features
  </a>
{% endblock %}

{% block scripts %}
<script>
$(document).ready(function(){
  $.getJSON("/home", function(data) {
    $('#features_link').append('<span class="badge">' + data.count + '</span>');
  });
});
</script>
{% endblock %}